import _ from 'lodash'

export default function filtered(props) {
  return _.omit(props, [
    // Input
    'improved',
    'improvedOnly',
    'fieldDef',
    'subscribeOnUpdate',
    'containerClass',
    'uuid',
    'field',
    '__type',
    'jobId',
    'dispatchSave',
    'dispatchLocal',
    'lookupPath',
    'showIf',
    'suffix',
    'options',
    'checkit',
    'validate',
    'hideField',
    'dispatch',
    'displayError',
    'error',
    'bare',
    'editable',
    'editableTitle',
    'helpBlock',
    'bareWithHelpBlock',
    'collection',
    `errorFormat`,
    `narrow`,
    `validateMessage`,
    `onErrorStateChange`,
    'printing',
    'lockMessage',
    'mirrorUpgrade',
    // Responsive field sizes
    'inputXs',
    'inputSm',
    'inputMd',
    'inputLg',
    'labelXs',
    'labelSm',
    'labelMd',
    'labelLg',

    // MenuItem
    'stageName',
    'stageId',
    'currentStageId',
    'companyId',
    'count',
    'dispatch',
    `sortBy`,
    `sortReverse`,
    `onSortChange`,
    `option`,
    'decimals',
    'createMask'
  ])
}
