import transitWriter from '../../server/src/helpers/transit-writer'
import {Map as IMap, fromJS} from 'immutable'

export const mockPayload = {
  jobs: {id: 1},
  accounts: {id: 1},
  companies: {id: 1},

  basedata: {job_id: 1},
  health: {job_id: 1},
  utilities: {job_id: 1},

  attic: [],
  dhw: [],
  door: [],
  freezer: [],
  hvac: [],
  refrigerator: [],
  vault: [],
  wall: [],
  window: [],
  caz: [],
  concern: [],
  oven: [],
  range: [],
  clothesDryer: [],

  recommendations: [],
}

export const hvacDefaults = {
  "uuid": "TESTING_UUID",
  "created_at":new Date(),
  "updated_at":new Date(),
  "deleted_at":null,
  "order":0,
  "job_id":1,
  "hvac_system_name":"Test System",
  "hvac_duct_leakage_value":null,
  "hvac_duct_location":null,
  "hvac_cooling_system_efficiency":null,
  "hvac_heating_system_model_year_improved":null,
  "hvac_percent_of_total_cooling_load_improved":null,
  "hvac_heating_system_manufacturer":null,
  "hvac_heating_system_manufacturer_improved":null,
  "hvac_percent_of_total_cooling_load":null,
  "hvac_heating_system_model_year":null,
  "hvac_cooling_system_efficiency_improved":null,
  "hvac_age_of_heating_equipment":null,
  "hvac_upgrade_action":null,
  "hvac_duct_location_improved":null,
  "hvac_duct_leakage_value_improved":null,
  "hvac_cooling_system_manufacturer":null,
  "hvac_system_equipment_type":null,
  "hvac_duct_insulation_improved":null,
  "hvac_percent_of_total_heating_load":null,
  "hvac_heating_system_efficiency_improved":null,
  "hvac_duct_leakage":null,
  "hvac_cooling_system_model":null,
  "hvac_cooling_system_model_year":null,
  "hvac_cooling_capacity":null,
  "hvac_age_of_cooling_equipment":null,
  "hvac_duct_insulation_value":null,
  "hvac_heat_pump_inverter_improved":null,
  "hvac_cooling_equipment_improved":null,
  "hvac_duct_efficiency_improved":null,
  "hvac_heating_capacity_improved":null,
  "hvac_heating_energy_source_improved":null,
  "hvac_heating_system_model":null,
  "hvac_heating_capacity":null,
  "hvac_heating_system_model_improved":null,
  "hvac_heating_energy_source":null,
  "hvac_duct_efficiency":null,
  "hvac_heating_equipment_improved":null,
  "hvac_cooling_equipment":null,
  "hvac_heat_pump_inverter":null,
  "hvac_dual_equipment":null,
  "hvac_duct_insulation_value_improved":null,
  "hvac_cooling_capacity_improved":null,
  "hvac_heating_system_efficiency":null,
  "hvac_cooling_system_model_year_improved":null,
  "hvac_cooling_system_model_improved":null,
  "hvac_duct_leakage_improved":null,
  "hvac_percent_of_total_heating_load_improved":null,
  "hvac_duct_insulation":null,
  "hvac_cooling_system_manufacturer_improved":null
}

// -- Fully mocking root state: --

export const TEST_ACCOUNT_1_ID = 1001;
export const TEST_ACCOUNT_2_ID = 1002;
export const TEST_JOB_ID = 2001;
export const TEST_COMPANY_ID = 3001;
export const TEST_PROGRAM_ID = 3002;
export const TEST_FINANCING_ID = 4001;
export const TEST_JOB_FINANCING_UUID = "e2dabc7b-db73-4e07-b173-69602b8ec326";

const account1Company1 = IMap({
  account_id: TEST_ACCOUNT_1_ID,
  company_id: TEST_COMPANY_ID
})
const account2Company1 = IMap({
  account_id: TEST_ACCOUNT_2_ID,
  company_id: TEST_COMPANY_ID
})

const company1Program1 = IMap({
  company_id: TEST_COMPANY_ID,
  program_id: 1
})
const company1Program2 = IMap({
  company_id: TEST_COMPANY_ID,
  program_id: TEST_PROGRAM_ID
})

const testCompany = fromJS({
  "company_photo_url": "http://www.ucarecdn.com/80e59541-1b21-48d0-b7b4-621d8150e8df/",
  "demo_company": 0,
  "notes": "Snugg Master Internal Account",
  "zip": "80302",
  "pricing_plan": null,
  "address_1": "123 Main Street",
  "address_2": "",
  "cached_stripe_exp": "12/2017",
  "cached_stripe_last4": "5086",
  "created_at": new Date(),
  "company_photo_uuid": "80e59541-1b21-48d0-b7b4-621d8150e8df",
  "city": "Boulder",
  "name": "Tunergy Audits, Inc",
  "stripe_id": "cus_2ACwwIOV7Po1sW",
  "phone": "(303) 872 7233",
  "hours_of_operation": "Mon-Fri 9am to 5pm",
  "state": "CO",
  "updated_at": new Date(),
  "deleted_at": null,
  "company_photo_name": "tunergy-2.png",
  "card_name": null,
  "source": null,
  "website": "snuggpro",
  "id": TEST_COMPANY_ID,
  "adgroup": null,
  "offer": null,
  "disabled": 0,
  "card_declined": 0
})

const testAccountAdmin = IMap({
  "last_login": null,
  "created_at": new Date(),
  "doe_assessor_id": "TST-SNUG-0000",
  "hours_of_operation": "",
  "program_admin": null,
  "last_name": "AccountAdmin",
  "role": "user",
  "program_id": null,
  "updated_at": new Date(),
  "title": "Account Admin",
  "deleted_at": null,
  "certifications": "My certs",
  "first_name": "Test",
  "phone_number": "(303) 810-6619",
  "id": TEST_ACCOUNT_1_ID,
  "gets_newsletter": 1,
  "email": "jeff@snugghome.com"
})
const testAccountUser = testAccountAdmin
  .set('id', TEST_ACCOUNT_2_ID)
  .set('last_name', 'AccountUser')

export const mockRootState = fromJS({
  "refrigerator": {
    "adfce75c-2cb3-4b2f-956f-9146745cea93": {
      "refrigerator_age": null,
      "refrigerator_size": null,
      "refrigerator_model_improved": null,
      "refrigerator_energy_star_improved": null,
      "refrigerator_usage": null,
      "refrigerator_usage_improved": null,
      "created_at": new Date(),
      "refrigerator_energy_star": null,
      "refrigerator_name": null,
      "refrigerator_model": null,
      "order": 0,
      "refrigerator_manufacturer": null,
      "refrigerator_model_year": null,
      "updated_at": new Date(),
      "refrigerator_model_year_improved": null,
      "deleted_at": null,
      "touched_fields": {},
      "refrigerator_manufacturer_improved": null,
      "uuid": "adfce75c-2cb3-4b2f-956f-9146745cea93",
      "job_id": TEST_JOB_ID
    }
  },
  "concern": {
    "e5467b53-5a48-4807-8247-c7b989d843b6": {
      "uuid": "e5467b53-5a48-4807-8247-c7b989d843b6",
      "job_id": TEST_JOB_ID,
      "order": 0,
      "created_at": new Date(),
      "updated_at": new Date(),
      "deleted_at": null,
      "concern_summary": null,
      "concern_detail": null
    }
  },
  "financingTemplates": IMap().set(1, fromJS({
    "rate": 3,
    "min_cash_down": "0",
    "created_at": new Date(),
    "term": "60",
    "account_id": null,
    "contact_info": "contact info",
    "eligibility": "eligibiily",
    "min_purchase": "10000",
    "min_fico_score": "680",
    "program_id": TEST_PROGRAM_ID,
    "closing_cost": "0",
    "updated_at": new Date(),
    "title": "Xcel Loan 1",
    "deleted_at": null,
    "type": "program",
    "id": TEST_FINANCING_ID,
    "max_purchase": "40000",
    "description": "description",
    "company_id": null
  })),
  "recommendationCaptionRows": {
    "65b7a2e6-486b-4ebf-9171-513d6440fd1c": {
      "left_photo_uuid": null,
      "recommendation_uuid": "74a9b1df-c5d2-4638-8b96-772dbe2e286e",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "65b7a2e6-486b-4ebf-9171-513d6440fd1c",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "6a1ea67e-3d27-4198-8d76-a830e04a6fe0": {
      "left_photo_uuid": null,
      "recommendation_uuid": "487355a2-6a50-4659-bc40-380ecc96e42b",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "6a1ea67e-3d27-4198-8d76-a830e04a6fe0",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "7de8fe7a-fa84-4d80-b39d-8945f51556b2": {
      "left_photo_uuid": null,
      "recommendation_uuid": "331d8bf2-f9e0-4780-bd5e-f592d247dbad",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "7de8fe7a-fa84-4d80-b39d-8945f51556b2",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "369721e9-9c67-402e-baee-c2d0b92c458a": {
      "left_photo_uuid": null,
      "recommendation_uuid": "fa1ec49e-06c0-4705-8d32-236ae533c853",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "369721e9-9c67-402e-baee-c2d0b92c458a",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "28649790-86b7-4e18-8aac-0aeceb79648a": {
      "left_photo_uuid": null,
      "recommendation_uuid": "1b079c20-702a-41f4-b417-339561380083",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "28649790-86b7-4e18-8aac-0aeceb79648a",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "516e01c6-f8fe-4ee3-91e8-a90a1ffe888b": {
      "left_photo_uuid": null,
      "recommendation_uuid": "61afd7fb-e3d6-41d7-b1c3-8d06f533f694",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "516e01c6-f8fe-4ee3-91e8-a90a1ffe888b",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "b7459859-d382-482d-992b-676f59489312": {
      "left_photo_uuid": null,
      "recommendation_uuid": "40c9a946-a528-42b5-af42-a4beae3db624",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "b7459859-d382-482d-992b-676f59489312",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "a215aaaa-0d8b-4495-b4f6-fffd0da91bec": {
      "left_photo_uuid": null,
      "recommendation_uuid": "c89cf5b3-57c1-4d5b-ac3d-8711e94aef3f",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "a215aaaa-0d8b-4495-b4f6-fffd0da91bec",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "c08ba31e-3f70-4662-83ff-987ce9afe7df": {
      "left_photo_uuid": null,
      "recommendation_uuid": "72686554-00df-4e3c-a519-4d6fc167f233",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "c08ba31e-3f70-4662-83ff-987ce9afe7df",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "ebc9181a-8011-4d6a-bd7c-e7a6688d70fe": {
      "left_photo_uuid": null,
      "recommendation_uuid": "bde69ed4-f212-404d-be21-0682e85e0b68",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "ebc9181a-8011-4d6a-bd7c-e7a6688d70fe",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "aba9f7bc-ddde-417e-9a8f-aaa4dfca6566": {
      "left_photo_uuid": null,
      "recommendation_uuid": "66cc3648-907c-44c8-a6e7-d2ca2d653fc0",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "aba9f7bc-ddde-417e-9a8f-aaa4dfca6566",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "3c98b167-4a47-4439-8344-c6408dba7698": {
      "left_photo_uuid": null,
      "recommendation_uuid": "0d500e20-ffbe-4154-b1bd-8900ab8ccf89",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "3c98b167-4a47-4439-8344-c6408dba7698",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "34aaf958-02f9-4d43-9bce-be5ad77ff34b": {
      "left_photo_uuid": null,
      "recommendation_uuid": "dee9d907-17e4-47c1-acf2-6e88a032e275",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "34aaf958-02f9-4d43-9bce-be5ad77ff34b",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "b40901e5-d204-49d0-b258-3ca835f735bc": {
      "left_photo_uuid": null,
      "recommendation_uuid": "b0a50a9f-26ac-47a7-b838-939e057ad042",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "b40901e5-d204-49d0-b258-3ca835f735bc",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "2ac8a36f-7dca-413a-9055-6252cf16539a": {
      "left_photo_uuid": null,
      "recommendation_uuid": "05f290c1-2e54-41b6-98c9-cd4cc8afe311",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "2ac8a36f-7dca-413a-9055-6252cf16539a",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "49fceacd-5fa3-4954-b63f-9991e5e8b2e7": {
      "left_photo_uuid": null,
      "recommendation_uuid": "9cec57f4-415e-41b4-bce2-c18e2c39ba99",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "49fceacd-5fa3-4954-b63f-9991e5e8b2e7",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "f7c026fd-9cc4-4e4e-a27e-d88d94ad4cab": {
      "left_photo_uuid": null,
      "recommendation_uuid": "011d47a0-6daf-499c-812a-f05c39284bf5",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "f7c026fd-9cc4-4e4e-a27e-d88d94ad4cab",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "0570d2f8-0547-496e-825b-128ca7f37b84": {
      "left_photo_uuid": null,
      "recommendation_uuid": "8bff765d-6057-40cb-b168-b3c4a816539c",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "0570d2f8-0547-496e-825b-128ca7f37b84",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "7a7b3d75-6a16-46d3-88af-4c0cf1f44036": {
      "left_photo_uuid": null,
      "recommendation_uuid": "107f88e9-2f8e-410a-a8a7-2cc4ebee44de",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "7a7b3d75-6a16-46d3-88af-4c0cf1f44036",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "1905dfb5-c38c-4881-b71b-c2d91119af9e": {
      "left_photo_uuid": null,
      "recommendation_uuid": "1d614dd5-c9a3-4d84-86b6-754228525433",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "1905dfb5-c38c-4881-b71b-c2d91119af9e",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "c3010c77-9861-45ab-9ec5-195cb179c370": {
      "left_photo_uuid": null,
      "recommendation_uuid": "15af626f-ed15-4348-a0d5-47e55d38d549",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "c3010c77-9861-45ab-9ec5-195cb179c370",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    },
    "c010f3a7-1856-49f5-b195-9dc69e2f478e": {
      "left_photo_uuid": null,
      "recommendation_uuid": "b6a02c16-96b1-4224-9eba-886ce91106f2",
      "left_photo_width": null,
      "caption": null,
      "created_at": new Date(),
      "left_photo_url": null,
      "right_photo_uuid": null,
      "left_photo_height": null,
      "order": 0,
      "left_photo_name": null,
      "right_photo_width": null,
      "right_photo_height": null,
      "updated_at": null,
      "deleted_at": null,
      "right_photo_name": null,
      "uuid": "c010f3a7-1856-49f5-b195-9dc69e2f478e",
      "job_id": TEST_JOB_ID,
      "right_photo_url": null
    }
  },
  "accounts": IMap()
    .set(TEST_ACCOUNT_1_ID, testAccountAdmin)
    .set(TEST_ACCOUNT_2_ID, testAccountUser),
  "companiesPrograms": IMap()
    .set(company1Program1, company1Program1)
    .set(company1Program2, company1Program2),
  "wall": {
    "13c005a4-e647-4c84-b405-bdf240244cf1": {
      "wall_continuous_insulation_improved": null,
      "walls_insulated": null,
      "wall_cavity_insulation": null,
      "wall_cavity_insulation_improved": null,
      "created_at": new Date(),
      "wall_continuous_insulation": null,
      "order": 0,
      "wall_system_percent_of_total": null,
      "wall_modeled_wall_area_improved": null,
      "wall_modeled_wall_area": null,
      "updated_at": new Date(),
      "deleted_at": null,
      "wall_exterior_wall_construction": null,
      "touched_fields": {},
      "uuid": "13c005a4-e647-4c84-b405-bdf240244cf1",
      "job_id": TEST_JOB_ID,
      "wall_exterior_wall_siding": null
    }
  },
  "utilities": IMap().set(TEST_JOB_ID, fromJS({
    "end_electric_date_3": null,
    "end_fuel_bill_3": null,
    "fuel_bill_units": "Therms",
    "end_electric_date_4": null,
    "end_fuel_bill_4": null,
    "lowest_monthly_natural_gas_bill": null,
    "end_electric_date_5": null,
    "end_fuel_bill_5": null,
    "end_electric_date_6": null,
    "end_fuel_bill_6": null,
    "electric_utility_provider_name": null,
    "end_electric_date_7": null,
    "fuel_account_number": null,
    "end_fuel_bill_7": null,
    "end_fuel_date_1": null,
    "end_electric_date_8": null,
    "end_fuel_bill_8": null,
    "start_electric_date_1": null,
    "highest_monthly_summer_electric_bill": null,
    "end_fuel_date_2": null,
    "end_electric_date_9": null,
    "end_fuel_bill_9": null,
    "end_fuel_date_3": null,
    "end_fuel_date_4": null,
    "end_fuel_date_5": null,
    "end_fuel_date_6": null,
    "lowest_monthly_electric_bill": null,
    "end_fuel_date_7": null,
    "end_fuel_date_10": null,
    "end_fuel_date_8": null,
    "start_fuel_date_1": null,
    "end_fuel_date_11": null,
    "end_fuel_date_9": null,
    "end_fuel_date_12": null,
    "highest_monthly_winter_natural_gas_bill": null,
    "end_fuel_bill_10": null,
    "end_electric_date_10": null,
    "simple_fuel_units": "Dollars",
    "end_fuel_bill_11": null,
    "end_electric_date_11": null,
    "end_fuel_bill_12": null,
    "end_electric_date_12": null,
    "total_simple_fuel_used_in_last_12_months": null,
    "end_electric_bill_1": null,
    "end_electric_bill_2": null,
    "electric_bill_units": "kWh",
    "end_electric_bill_10": null,
    "primary_heating_fuel_type": null,
    "end_electric_bill_3": null,
    "end_electric_bill_11": null,
    "end_electric_bill_4": null,
    "end_electric_bill_12": null,
    "end_electric_bill_5": null,
    "highest_monthly_winter_electric_bill": null,
    "end_electric_bill_6": null,
    "fuel_utility_provider_name": null,
    "job_id": TEST_JOB_ID,
    "electric_account_number": null,
    "end_electric_bill_7": null,
    "end_electric_date_1": null,
    "end_fuel_bill_1": null,
    "end_electric_bill_8": null,
    "end_electric_date_2": null,
    "bill_entry_type": null,
    "end_fuel_bill_2": null,
    "end_electric_bill_9": null
  })),
  "door": {
    "0492427a-b62a-4f64-83ce-54a75990d627": {
      "created_at": new Date(),
      "door_type": null,
      "door_area_improved": null,
      "order": 0,
      "door_energy_star_improved": null,
      "door_u_value_improved": null,
      "door_u_value": null,
      "updated_at": new Date(),
      "door_energy_star": null,
      "deleted_at": null,
      "touched_fields": {},
      "uuid": "0492427a-b62a-4f64-83ce-54a75990d627",
      "job_id": TEST_JOB_ID,
      "door_area": null
    }
  },
  "totals": IMap().set(TEST_JOB_ID, fromJS({
    "installed_costs": null,
    "annual_electric_kWh_used": null,
    "annual_electric_dollars_spent": null,
    "saved_kwh": null,
    "payback_years": null,
    "saved_kwh_percent": null,
    "annual_fuel_therms_used": null,
    "saved_mbtu": null,
    "yearly_energy_cost": null,
    "annual_electric_kWh_improved": null,
    "saved_co2_tons": null,
    "saved_co2_percent": null,
    "saved_mbtu_percent": null,
    "total_co2_tons": null,
    "mbtu_improved": null,
    "annual_electric_dollars_improved": null,
    "updated_at": null,
    "annual_fuel_therms_saved": null,
    "mbtu_base": null,
    "annual_fuel_therms_improved": null,
    "total_co2_tons_base": null,
    "mirr": null,
    "sir": null,
    "yearly_energy_cost_improved": null,
    "job_id": TEST_JOB_ID,
    "annual_fuel_dollars_improved": null,
    "annual_fuel_dollars_spent": null,
    "touched": 0,
    "total_savings": null
  })),
  "hvac": {},
  "window": {
    "7b281367-f9b5-4f8f-9cbe-dfdf1b8ee4eb": {
      "window_area_east": null,
      "window_area_south_improved": null,
      "window_area_north": null,
      "window_exterior_treatment_west_improved": null,
      "window_east_area_percent": null,
      "window_exterior_treatment_west": null,
      "window_area_north_improved": null,
      "window_type": null,
      "created_at": new Date(),
      "window_area_south": null,
      "window_south_overhang_depth": null,
      "window_west_overhang_depth": null,
      "window_area_east_improved": null,
      "window_exterior_treatment_north": null,
      "order": 0,
      "window_energy_star_improved": null,
      "window_area_west": null,
      "window_efficiency_improved": null,
      "window_north_overhang_depth": null,
      "window_solar_heat_gain_coefficient_improved": null,
      "window_south_area_percent": null,
      "window_west_area_percent": null,
      "window_exterior_treatment_south": null,
      "window_exterior_treatment_east_improved": null,
      "window_exterior_treatment_east": null,
      "updated_at": new Date(),
      "window_exterior_treatment_south_improved": null,
      "window_solar_heat_gain_coefficient": null,
      "window_efficiency": null,
      "window_area_west_improved": null,
      "deleted_at": null,
      "touched_fields": {},
      "window_energy_star": null,
      "uuid": "7b281367-f9b5-4f8f-9cbe-dfdf1b8ee4eb",
      "window_north_area_percent": null,
      "job_id": TEST_JOB_ID,
      "window_east_overhang_depth": null,
      "window_frame": null,
      "window_exterior_treatment_north_improved": null
    }
  },
  "vault": {
    "f8d6c8eb-a9ec-47f9-83aa-c37b652fe6b6": {
      "vault_roof_absorptance_improved": null,
      "created_at": new Date(),
      "vault_roof_absorptance": null,
      "vault_cavity_insulation": null,
      "vault_roof_emissivity_improved": null,
      "vault_modeled_vault_area_improved": null,
      "order": 0,
      "vault": null,
      "vault_continuous_insulation": null,
      "updated_at": new Date(),
      "vault_continuous_insulation_improved": null,
      "vault_percent": null,
      "deleted_at": null,
      "touched_fields": {},
      "uuid": "f8d6c8eb-a9ec-47f9-83aa-c37b652fe6b6",
      "job_id": TEST_JOB_ID,
      "vault_cool_roof": null,
      "vault_modeled_vault_area": null,
      "vault_roof_emissivity": null,
      "vault_cavity_insulation_improved": null
    }
  },
  "dhw": {
    "41ffa7f1-9e4b-497e-bdb8-903c5fb2078b": {
      "dhw_temp": null,
      "dhw_location": null,
      "dhw_tank_size_improved": null,
      "dhw_fuel": null,
      "dhw_type": null,
      "created_at": new Date(),
      "dhw_tank_size": null,
      "dhw_temp_improved": null,
      "dhw_percent_load": null,
      "dhw_model_year_improved": null,
      "dhw_model_improved": null,
      "dhw_manufacturer_improved": null,
      "dhw_energy_star_improved": null,
      "order": 0,
      "dhw_energy_factor_improved": null,
      "dhw_type_2_improved": null,
      "dhw_heating_capacity": null,
      "dhw_age": null,
      "dhw_fuel_2": null,
      "dhw_fuel_2_improved": null,
      "updated_at": new Date(),
      "dhw_heating_capacity_improved": null,
      "dhw_type_2": null,
      "deleted_at": null,
      "dhw_energy_factor": null,
      "touched_fields": {},
      "dhw_temperature_settings": null,
      "uuid": "41ffa7f1-9e4b-497e-bdb8-903c5fb2078b",
      "dhw_manufacturer": null,
      "dhw_model": null,
      "job_id": TEST_JOB_ID,
      "dhw_energy_star": null,
      "dhw_percent_load_improved": null,
      "dhw_model_year": null
    }
  },
  "accountsCompanies": IMap()
    .set(account1Company1, account1Company1.set('role', 'admin'))
    .set(account2Company1, account2Company1.set('role', 'user')),
  "jobs": IMap().set(TEST_JOB_ID, fromJS({
    "creator_account_id": TEST_ACCOUNT_1_ID,
    "zip": "80302",
    "has_calculated": 0,
    "address_1": "1021 Pearl St",
    "created_by_program_id": TEST_PROGRAM_ID,
    "address_2": null,
    "sample_job": 0,
    "created_at": new Date(),
    "city": "Boulder",
    "from_template_id": null,
    "account_id": TEST_ACCOUNT_1_ID,
    "home_phone": "5555551212",
    "is_calculating": 0,
    "created_by_company_id": TEST_COMPANY_ID,
    "is_template": 0,
    "state": "CO",
    "upgrade_notes_hvac": null,
    "from_job_id": null,
    "last_name": "User",
    "program_id": TEST_PROGRAM_ID,
    "service_time": null,
    "updated_at": null,
    "version": 5,
    "deleted_at": null,
    "first_name": "Test",
    "renter_owner": 0,
    "id": TEST_JOB_ID,
    "stage_id": null,
    "email": "test@example.com",
    "company_id": TEST_COMPANY_ID,
    "deleted_by": null,
    "created_by_account_id": TEST_ACCOUNT_1_ID,
    "bill_entry_type": null
  })),
  "jobFinancing": {
    [TEST_JOB_FINANCING_UUID]: {
      "rate": 3.2,
      "min_cash_down": "20",
      "from_financing_template_id": null,
      "total_cost": null,
      "created_at": "2016-05-16T19:57:52.000Z",
      "term": "20",
      "contact_info": "Test",
      "eligibility": "Test",
      "min_purchase": "300",
      "cash_down": null,
      "order": 3,
      "min_fico_score": "650",
      "closing_cost": "Min $20 / Max $80",
      "updated_at": null,
      "title": "Some Financing",
      "deleted_at": null,
      "uuid": TEST_JOB_FINANCING_UUID,
      "max_purchase": "2000",
      "is_shown": 0,
      "description": "Test",
      "job_id": 41762
    }
  },
  "recommendations": {
    "40c9a946-a528-42b5-af42-a4beae3db624": {
      "created_at": new Date(),
      "cost": null,
      "order": 19,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Set water heater to deliver at 122 F (use a cooking thermometer to test the temperature at the faucet) or the lowest practical setting for your preferences. A good measure is if you can take a shower using only hot water (not adding cold water), but still above 122 F. This will reduce standby energy loss and risk of scalding.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 7,
      "title": "Lower Hot Water Temp",
      "savings": null,
      "deleted_at": null,
      "uuid": "40c9a946-a528-42b5-af42-a4beae3db624",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "1b079c20-702a-41f4-b417-339561380083": {
      "created_at": new Date(),
      "cost": null,
      "order": 4,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Install a more efficient air conditioner or evaporative cooler. Depending on the age of the unit, substantial savings may be gained by replacing it with an ENERGY STAR rated appliance. If it doesn't quite make sense to replace your air conditioner now, be prepared to choose a high efficiency ENERGY STAR unit (14 SEER or higher) when it finally wears out.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 4,
      "title": "Upgrade Cooling System",
      "savings": null,
      "deleted_at": null,
      "uuid": "1b079c20-702a-41f4-b417-339561380083",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "107f88e9-2f8e-410a-a8a7-2cc4ebee44de": {
      "created_at": new Date(),
      "cost": null,
      "order": 10,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Compact Florescent Lightbulbs (CFLs) use 1/4 of the energy of regular incandescent light bulbs and last 8 to 15 times as long. Light Emitting Diode (LED) bulbs use 12% of the energy of regular incandescent light bulbs and last up to 50 times as long. Replacing incandescent bulbs with CFLs or LEDs will save significant energy and replacement costs over time.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 13,
      "title": "Upgrade Lighting",
      "savings": null,
      "deleted_at": null,
      "uuid": "107f88e9-2f8e-410a-a8a7-2cc4ebee44de",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "bde69ed4-f212-404d-be21-0682e85e0b68": {
      "created_at": new Date(),
      "cost": null,
      "order": 14,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Vaulted ceilings are almost always poorly insulated. If your roof is in need of replacement, it's a perfect time to also insulate the area between the interior drywall and the roof deck. Dense packing this cavity with blown fiberglass or cellulose will help prevent significant heat loss.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 20,
      "title": "Insulate Vault",
      "savings": null,
      "deleted_at": null,
      "uuid": "bde69ed4-f212-404d-be21-0682e85e0b68",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "74a9b1df-c5d2-4638-8b96-772dbe2e286e": {
      "created_at": new Date(),
      "cost": null,
      "order": 12,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Insulating your walls can lead to a significant reduction in utility bills. The is done by drilling small holes in the wall cavities either from the inside or outside and filling the space with cellulose, fiberglass, or even foam insulation. If it's time to replace your exterior siding, then be sure to ask your contractor about adding a layer of rigid foam underneath the new sheathing of 1\" or more.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 16,
      "title": "Insulate Walls",
      "savings": null,
      "deleted_at": null,
      "uuid": "74a9b1df-c5d2-4638-8b96-772dbe2e286e",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "fa1ec49e-06c0-4705-8d32-236ae533c853": {
      "created_at": new Date(),
      "cost": null,
      "order": 15,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Insulating and \"conditioning\" your crawl space will increase the overall temperature of the space and make the floors above it more comfortable. Crawlspaces can be converted from an unconditioned to a conditioned space which includes sealing off any vents to the outside, insulating the foundation walls, and installing a vapor barrier on top of the dirt floor. It often includes adding a jump vent to the main conditioned space in the house or ducting the furnace and/or A/C into the crawlspace as well.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 5,
      "title": "Insulate Crawl Space",
      "savings": null,
      "deleted_at": null,
      "uuid": "fa1ec49e-06c0-4705-8d32-236ae533c853",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "dee9d907-17e4-47c1-acf2-6e88a032e275": {
      "created_at": new Date(),
      "cost": null,
      "order": 5,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "If you have a forced air system for heating or cooling, sealing the connections and penetrations with mastic will ensure that all of the air makes it to where it was designed to go. This increases the efficiency of your heating and cooling system and improves comfort. If you have a boiler system for heating, insulating the pipes will increase the effectiveness of the system.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 9,
      "title": "Seal Duct Work",
      "savings": null,
      "deleted_at": null,
      "uuid": "dee9d907-17e4-47c1-acf2-6e88a032e275",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "487355a2-6a50-4659-bc40-380ecc96e42b": {
      "created_at": new Date(),
      "cost": null,
      "order": 16,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Insulating your basement walls will increase the overall temperature of your basement and make the floors above more comfortable. A fiberglass blanket with a vinyl backing can be installed along the basement walls. Or the walls can be framed out, insulated, and finished with drywall to make a \"finished basement\".",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 3,
      "title": "Insulate Basement",
      "savings": null,
      "deleted_at": null,
      "uuid": "487355a2-6a50-4659-bc40-380ecc96e42b",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "8bff765d-6057-40cb-b168-b3c4a816539c": {
      "created_at": new Date(),
      "cost": null,
      "order": 17,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Adding storm windows, solar screens or replacing your current windows can save energy and help reduce drafts or solar gain.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 17,
      "title": "Upgrade Windows",
      "savings": null,
      "deleted_at": null,
      "uuid": "8bff765d-6057-40cb-b168-b3c4a816539c",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "61afd7fb-e3d6-41d7-b1c3-8d06f533f694": {
      "created_at": new Date(),
      "cost": null,
      "order": 9,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Old refrigerators can often cost twice as much to operate as a new refrigerator. Replace your old refrigerator with a new ENERGY STAR model and be sure to recycle the old one (keeping it running in your garage or basement will use even more energy).",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 14,
      "title": "Refrigerator",
      "savings": null,
      "deleted_at": null,
      "uuid": "61afd7fb-e3d6-41d7-b1c3-8d06f533f694",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "c89cf5b3-57c1-4d5b-ac3d-8711e94aef3f": {
      "created_at": new Date(),
      "cost": null,
      "order": 2,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Installing a programmable thermostat (or correctly setting the one you currently have) will help you to use less energy when you're not at home or when you're sleeping.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 15,
      "title": "Thermostat Set Points",
      "savings": null,
      "deleted_at": null,
      "uuid": "c89cf5b3-57c1-4d5b-ac3d-8711e94aef3f",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "331d8bf2-f9e0-4780-bd5e-f592d247dbad": {
      "created_at": new Date(),
      "cost": null,
      "order": 8,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Old clothes washers can be energy and water hogs. When your current clothes washer breaks or otherwise needs to be replaced, be sure to choose a front loading ENERGY STAR model with the highest Modified Energy Factor (MEF) that's within your budget. More information is available at http://www.energystar.gov.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 23,
      "title": "Upgrade Clotheswasher",
      "savings": null,
      "deleted_at": null,
      "uuid": "331d8bf2-f9e0-4780-bd5e-f592d247dbad",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "66cc3648-907c-44c8-a6e7-d2ca2d653fc0": {
      "created_at": new Date(),
      "cost": null,
      "order": 22,
      "touched_cost": null,
      "status": 4,
      "why_it_matters": null,
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 18,
      "title": "Health & Safety",
      "savings": null,
      "deleted_at": null,
      "uuid": "66cc3648-907c-44c8-a6e7-d2ca2d653fc0",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "15af626f-ed15-4348-a0d5-47e55d38d549": {
      "created_at": new Date(),
      "cost": null,
      "order": 3,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Install a more efficient furnace, boiler or heat pump. Depending on the age of the unit, substantial savings may be gained by replacing it with an ENERGY STAR rated appliance. If you're heating with gas, look for a sealed combustion unit. They're much safer since the exhaust pathway from the unit is sealed and goes directly outside. If it doesn't quite make sense to replace your heating system now, be prepared to replace it with a high efficiency ENERGY STAR unit when it finally wears out.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 12,
      "title": "Upgrade Heating System",
      "savings": null,
      "deleted_at": null,
      "uuid": "15af626f-ed15-4348-a0d5-47e55d38d549",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "b6a02c16-96b1-4224-9eba-886ce91106f2": {
      "created_at": new Date(),
      "cost": null,
      "order": 21,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Single-speed pool pumps can often equate to half of an entire home's electricity demand. Substantial energy savings can be achieved by replacing it with a variable speed pool pump.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 21,
      "title": "Upgrade Pool Pump",
      "savings": null,
      "deleted_at": null,
      "uuid": "b6a02c16-96b1-4224-9eba-886ce91106f2",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "b0a50a9f-26ac-47a7-b838-939e057ad042": {
      "created_at": new Date(),
      "cost": null,
      "order": 7,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Old dishwashers can be energy and water hogs. When your current dishwasher breaks or otherwise needs to be replaced, be sure to choose an ENERGY STAR model with the highest Energy Factor (EF) that's within your budget. More information is available at http://www.energystar.gov.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 22,
      "title": "Upgrade Dishwasher",
      "savings": null,
      "deleted_at": null,
      "uuid": "b0a50a9f-26ac-47a7-b838-939e057ad042",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "05f290c1-2e54-41b6-98c9-cd4cc8afe311": {
      "created_at": new Date(),
      "cost": null,
      "order": 6,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Old freezers can easily cost twice as much to operate as a new freezers. Replace your old freezer with a new ENERGY STAR model and be sure to recycle the old one (keeping it running in your garage or basement will use even more energy).",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 11,
      "title": "Replace Freezer",
      "savings": null,
      "deleted_at": null,
      "uuid": "05f290c1-2e54-41b6-98c9-cd4cc8afe311",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "72686554-00df-4e3c-a519-4d6fc167f233": {
      "created_at": new Date(),
      "cost": null,
      "order": 1,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Insulating floors above the garage and cantilevers can dramatically increase the comfort of bedrooms and other living spaces. This is done by drilling holes in the ceiling of the garage or floor of the cantilever and then filling the cavity between the floor joists with blown-in insulation.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 10,
      "title": "Insulate Frame Floor",
      "savings": null,
      "deleted_at": null,
      "uuid": "72686554-00df-4e3c-a519-4d6fc167f233",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "011d47a0-6daf-499c-812a-f05c39284bf5": {
      "created_at": new Date(),
      "cost": null,
      "order": 18,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Air sealing is typically the most cost effective improvement you can make to your home. To properly seal out air leaks, a large fan called a blower door is used to depressurize your house. This makes air leaks easy to find, so corrective measures can be taken. A good air sealing job will dramatically increase the comfort of your home and help you save significant energy.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 1,
      "title": "Seal Air Leaks",
      "savings": null,
      "deleted_at": null,
      "uuid": "011d47a0-6daf-499c-812a-f05c39284bf5",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "0d500e20-ffbe-4154-b1bd-8900ab8ccf89": {
      "created_at": new Date(),
      "cost": null,
      "order": 20,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Replace your water heater with a tankless model or a heat pump water heater to save energy and reduce the ability for dangerous Carbon Monoxide to leak into your home.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 6,
      "title": "Upgrade Water Heater",
      "savings": null,
      "deleted_at": null,
      "uuid": "0d500e20-ffbe-4154-b1bd-8900ab8ccf89",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "9cec57f4-415e-41b4-bce2-c18e2c39ba99": {
      "created_at": new Date(),
      "cost": null,
      "order": 11,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Adding storm door(s) or replacing your current exterior door(s) with insulated ones will help save energy and help reduce drafts.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 8,
      "title": "Replace Doors or Add Storm Doors",
      "savings": null,
      "deleted_at": null,
      "uuid": "9cec57f4-415e-41b4-bce2-c18e2c39ba99",
      "sir": null,
      "job_id": TEST_JOB_ID
    },
    "1d614dd5-c9a3-4d84-86b6-754228525433": {
      "created_at": new Date(),
      "cost": null,
      "order": 13,
      "touched_cost": null,
      "status": 0,
      "why_it_matters": "Adding insulation to your attic can lead to a significant reduction in your utility bills. This process is often combined with careful air sealing of the ceiling from the attic side to ensure the new insulation perform at its maximum level.",
      "homeowner_notes": null,
      "contractor_notes": null,
      "updated_at": null,
      "rec_definition_id": 2,
      "title": "Insulate Attic",
      "savings": null,
      "deleted_at": null,
      "uuid": "1d614dd5-c9a3-4d84-86b6-754228525433",
      "sir": null,
      "job_id": TEST_JOB_ID
    }
  },
  "invitations": {},
  "freezer": {},
  "companies": IMap().set(TEST_COMPANY_ID, testCompany),
  "basedata": IMap().set(TEST_JOB_ID, fromJS({
    "percent_of_ceilings_shared": null,
    "n_factor": null,
    "dishwasher_installed": "Yes",
    "dishwasher_manufacturer_improved": null,
    "crawl_cavity_insulation": null,
    "number_of_cfls_or_leds": null,
    "basement_cooling_improved": "Intentional",
    "type_of_home": null,
    "basement_cavity_insulation_improved": null,
    "cooling_setpoint_low_improved": null,
    "equivalent_ach_50_improved": null,
    "basement_heating": "Intentional",
    "design_temp_winter_indoor": null,
    "includes_basement": null,
    "basement_rim_joist_insulation": null,
    "wind_zone": "2",
    "effective_leakage_area_improved": null,
    "tuck_under_garage": null,
    "pool_size": null,
    "number_of_occupants": null,
    "modeled_basement_perimeter": null,
    "basement_rim_joist_treatment": "Same as Basement Wall",
    "floor_cavity_insulation_improved": null,
    "heating_setpoint_high_improved": null,
    "house_length": null,
    "pool_pump_manufacturer": null,
    "clothes_washer_energy_usage_improved": null,
    "pool_pump_turnover": null,
    "pool_pump_manufacturer_improved": null,
    "foundation_slab": null,
    "utility_price_pellets": null,
    "pv": null,
    "basement_rim_joist_treatment_improved": "Same as Basement Wall",
    "pool_pump_turnover_improved": null,
    "heating_setpoint_high": null,
    "floor_cavity_insulation": null,
    "house_width": null,
    "utility_price_electricity": null,
    "basement_rim_joist_insulation_improved": null,
    "effective_leakage_area": null,
    "basement_heating_improved": "Intentional",
    "percent_cfls_or_leds": null,
    "equivalent_ach_50": null,
    "number_of_bedrooms": null,
    "cooling_setpoint_low": null,
    "basement_cavity_insulation": null,
    "modeled_basement_wall_area": null,
    "demand_k_w_savings": null,
    "crawlspace_rim_joist_length": null,
    "basement_cooling": "Intentional",
    "dishwasher_manufacturer": null,
    "dishwasher_installed_improved": "Yes",
    "number_of_cfls_or_leds_improved": null,
    "crawl_cavity_insulation_improved": null,
    "foundation_crawlspace": null,
    "design_temp_winter_outdoor": null,
    "utility_price_propane": null,
    "percent_cfl_or_led_improved": null,
    "dishwasher_model_year": null,
    "dishwasher_energy_factor": null,
    "crawl_wall_insulation": null,
    "equivalent_nach": null,
    "floor_continuous_insulation": null,
    "shared_walls_east": null,
    "clothes_washer_energy_star": null,
    "cooling_setpoint_high": null,
    "clothes_washer_manufacturer": null,
    "clothes_washer_model": null,
    "clothes_washer_water_usage_improved": null,
    "programmable_thermostat_installed": null,
    "pool_pump_type": null,
    "pool_pump_horsepower_improved": null,
    "demand_k_w": null,
    "modeled_crawl_floor_area": null,
    "clothes_washer_model_year": null,
    "percent_of_floors_shared": null,
    "hot_tub": null,
    "blower_door_reading_improved": null,
    "dishwasher_energy_star": null,
    "heating_setpoint_low": null,
    "pool_pump_hours_improved": null,
    "basement_continuous_insulation": null,
    "crawlspace_insulation": null,
    "dishwasher_model": null,
    "crawlspace_type_improved": null,
    "number_of_leds_improved": null,
    "heating_design_load_improved": null,
    "cooling_latent_design_load_improved": null,
    "pv_production": null,
    "utility_price_fuel_oil": null,
    "number_of_incandescents": null,
    "conditioned_area": null,
    "clothes_washer_mef": null,
    "pool_pump_days_per_year": null,
    "crawlspace_rim_joist_insulation": null,
    "modeled_crawl_wall_area": null,
    "conditioned_air_volume": null,
    "cooling_sensible_design_load_improved": null,
    "total_number_of_light_bulbs": null,
    "basement_wall_insulation": null,
    "shared_walls_north": null,
    "crawlspace_rim_joist_treatment": "Same as Crawl Wall",
    "pool_pump_model": null,
    "clothes_washer_type_improved": null,
    "utility_price_wood": null,
    "pool_pump_model_improved": null,
    "clothes_washer_type": null,
    "design_temp_summer_outdoor": null,
    "crawlspace_rim_joist_treatment_improved": "Same as Crawl Wall",
    "cooling_sensible_design_load": null,
    "total_number_of_light_bulbs_improved": null,
    "skylight_area": null,
    "front_of_building_orientation": null,
    "number_of_cfls_installed": null,
    "modeled_floor_area": null,
    "crawlspace_rim_joist_insulation_improved": null,
    "pool_pump_days_per_year_improved": null,
    "garage_size": null,
    "modeled_basement_floor_area": null,
    "basement_rim_joist_length": null,
    "clothes_washer_mef_improved": null,
    "number_of_incandescents_improved": null,
    "shielding": "Normal",
    "design_temp_summer_indoor": null,
    "touched_fields": {},
    "heating_design_load": null,
    "average_wall_height": null,
    "number_of_leds": null,
    "crawlspace_type": null,
    "utility_price_natural_gas": null,
    "cooling_latent_design_load": null,
    "basement_continuous_insulation_improved": null,
    "foundation_basement": null,
    "heating_setpoint_low_improved": null,
    "pool_pump_hours": null,
    "dishwasher_energy_star_improved": null,
    "blower_door_reading": null,
    "dishwasher_model_improved": null,
    "pool": null,
    "clothes_washer_model_year_improved": null,
    "demand_k_w_improved": null,
    "pool_pump_horsepower": null,
    "year_built": null,
    "job_id": TEST_JOB_ID,
    "shared_walls_south": null,
    "floors_above_grade": null,
    "pool_pump_type_improved": null,
    "foundation_above_grade_height": null,
    "number_of_units": null,
    "clothes_washer_model_improved": null,
    "clothes_washer_manufacturer_improved": null,
    "cooling_setpoint_high_improved": null,
    "clothes_washer_energy_star_improved": null,
    "floor_continuous_insulation_improved": null,
    "equivalent_nach_improved": null,
    "crawl_wall_insulation_improved": null,
    "dishwasher_energy_factor_improved": null,
    "shared_walls_west": null,
    "percent_cfl_or_led": null,
    "dishwasher_model_year_improved": null
  })),
  "clothesDryer": {
    "c99881f3-9e63-4051-a3b5-5f9b11428b57": {
      job_id: TEST_JOB_ID,
      order: 0,
      uuid: "c99881f3-9e63-4051-a3b5-5f9b11428b57",
      "clothes_dryer_fuel_type": null,
    }
  },
  "oven": {
    "81b2dc90-82b9-4c9e-b153-2e5e26fdba1f": {
      job_id: TEST_JOB_ID,
      order: 0,
      uuid: '81b2dc90-82b9-4c9e-b153-2e5e26fdba1f',
      oven_fuel_type: null,
    },
  },
  "range": {
    "fcdf5daa-ddce-4b5c-bb20-298404cd3e68": {
      job_id: TEST_JOB_ID,
      order: 0,
      uuid: 'fcdf5daa-ddce-4b5c-bb20-298404cd3e68',
      range_fuel_type: null,
    },
  },
  "attic": {
    "f917a3b1-20a0-4385-9700-ca29d3bce42b": {
      "attic_roof_absorptance": null,
      "attic_knee_wall_area_improved": null,
      "attic_percent": null,
      "attic_radiant_barrier_improved": null,
      "attic_roof_emissivity_improved": null,
      "attic_insulation_type": null,
      "attic_cool_roof": null,
      "attic_insulation_type_improved": null,
      "attic_radiant_barrier": null,
      "attic_roof_emissivity": null,
      "created_at": new Date(),
      "attic_roof_absorptance_improved": null,
      "attic_knee_wall_area": null,
      "attic_modeled_attic_area": null,
      "attic_knee_wall_insulation": null,
      "order": 0,
      "attic_insulation": null,
      "attic_insulation_improved": null,
      "updated_at": new Date(),
      "attic_insulation_depth": null,
      "deleted_at": null,
      "touched_fields": {},
      "uuid": "f917a3b1-20a0-4385-9700-ca29d3bce42b",
      "job_id": TEST_JOB_ID,
      "attic_has_knee_wall": null,
      "attic_knee_wall_insulation_improved": null,
      "attic_modeled_attic_area_improved": null
    }
  },
  "health": IMap([
    [TEST_JOB_ID, {
      "health_mold_moisture": null,
      "health_draft_pressure": null,
      "health_venting": null,
      "health_electrical": null,
      "health_gas_leak": null,
      "health_worst_case_depressurization": null,
      "health_natural_condition_spillage": null,
      "health_radon": null,
      "health_worst_case_spillage": null,
      "job_id": TEST_JOB_ID,
      "health_ambient_carbon_monoxide": null,
      "health_asbestos": null,
      "health_undiluted_flue_co": null,
      "health_lead": null
    }]
  ]),
  "caz": {
    "0b6be22f-3f64-4f62-828c-d4941682c651": {
      "caz_appliance_flue_current_condition": null,
      "caz_poor_case_test": null,
      "created_at": new Date(),
      "caz_appliance_co_test_result": null,
      "caz_fuel_leaks_addressed_improved": null,
      "caz_water_heater_orphaned_improved": null,
      "caz_name": null,
      "order": 0,
      "caz_appliance_co_poor_scenario": null,
      "caz_fuel_leaks_identified": null,
      "caz_max_ambient_co": null,
      "caz_appliance_spillage_test_result": null,
      "caz_appliance_vent_system_type": null,
      "caz_appliance_spillage_poor_condition": null,
      "caz_appliance_vent_system_type_improved": null,
      "caz_ambient_co": null,
      "caz_appliance_co_current_condition": null,
      "updated_at": new Date(),
      "caz_appliance_spillage_test_result_improved": null,
      "deleted_at": null,
      "caz_fuel_leaks_identified_improved": null,
      "uuid": "0b6be22f-3f64-4f62-828c-d4941682c651",
      "job_id": TEST_JOB_ID,
      "caz_notes": null,
      "caz_appliance_spillage_current_condition": null,
      "caz_water_heater_orphaned": null,
      "caz_fuel_leaks_addressed": null,
      "caz_appliance_co_test_result_improved": null
    }
  },
  "cazSystem": {},
  "reports": IMap().set(TEST_JOB_ID, fromJS({
    "cover_photo_name": null,
    "serviced_by_title": "Audited By",
    "page_rebates": 1,
    "page_concerns": 1,
    "page_coc": 1,
    "title_coc": "Certificate of Completion",
    "element_co2": 1,
    "element_costs": 2,
    "element_photos": 1,
    "title_glossary": "Glossary",
    "safety_overview": "<div><h3>What's This?</h3><p>These tests are recommended by the Building Performance Institute (BPI). They can help identify potential health and safety concerns in your home.</p></div>",
    "toggled_elements": null,
    "page_hes": 1,
    "element_now_and_goal": 1,
    "page_financing": 1,
    "page_cover": 1,
    "additional_notes_overview_title": "About this section",
    "theme": 1,
    "title_rebates": "Rebates & Incentives",
    "page_solutions": 1,
    "element_program_info": 1,
    "page_health": 1,
    "title_additional": "Additional Notes",
    "page_glossary": 1,
    "additional_notes_overview": "Additional notes are miscellaneous items that deserve a mention in your home's report.\n\nThese mentioned items are not included in the cost or savings of your project.",
    "title_hes": "Home Energy Score",
    "page_upgrade_details": 1,
    "concerns_sidebar": "<div> <h3>We listened to you!</h3> <p>As our client, we want to make sure we are addressing all of your concerns for your home. If we have missed any concerns in this report, please let us know right away.</p> </div>",
    "title_financing": "Financing",
    "element_sort_order": [
      "element_photos",
      "element_homeowner_notes",
      "element_contractor_notes",
      "element_now_and_goal"
    ],
    "title_cover": "Your Energy Audit",
    "cover_photo_uuid": null,
    "service_date_title": "Audit Date",
    "element_homeowner_notes": 1,
    "title_solutions": "Solutions for Your Home",
    "page_metrics": 1,
    "solutions_title": "Call us today at (303) 872 7233 to ask a question or discuss the next step!",
    "approximate_cost_text": null,
    "toggled_pages": null,
    "estimated_savings_text": null,
    "title_tech_specs": "Tech Specs",
    "element_savings": 1,
    "cover_text_area": null,
    "updated_at": null,
    "element_why_it_matters": 1,
    "page_additional_notes": 1,
    "element_sir": 1,
    "element_contractor_notes": 1,
    "cover_photo_url": null,
    "title_concerns": "Concerns",
    "title_metrics": "Metrics",
    "job_id": TEST_JOB_ID,
    "page_sort_order": [
      "page_cover",
      "page_financing",
      "page_concerns",
      "page_solutions",
      "page_upgrade_details",
      "page_health",
      "page_additional_notes",
      "page_rebates",
      "page_tech_specs",
      "page_metrics",
      "page_glossary"
    ],
    "page_tech_specs": 1
  }))
})

export const mockBootstrap = transitWriter(mockRootState)
